### ISSUE TITLE
[0.28.1] Node16 on Alpine suffers SIGSEGV error when using argon2 verify

### ISSUE THREAD

**Issue by Tallyrald** [ranisalt/node-argon2#302]
### Steps to reproduce
1. Call the argon2.verify function on Node v16.X.X on alpine linux using argon2 v0.28.1

[Click here for reproduction repository](https://github.com/Tallyrald/argon2-sigsegv-repro)

### Expected behaviour
Verify function returns either true or false.

### Actual behaviour
Node exits with SIGSEGV signal.

### Environment
**Operating system**: Alpine linux (official node docker container)

**Node version:** 16.X.X

I'm using Typescript v4.3.2

Issue is specific to Node16 & argon2 v0.28.1. Node14 works fine as well as argon2 v0.27.2 (even on Node16).
I'm not sure whether the verify function is the actual or only culprit, but I've seen in my own application that Node definitely crashes while using this function.

**Comment by LoicMatters** [comment]
Hello, any update on this ? Got the same problem today on node 16 running on alpine linux with the 0.28.3 package version.

**Comment by Janl1** [comment]
Can confirm the issue. Downgrading to v0.27.2 solves it temporarily.

**Comment by ranisalt** [comment]
I can reproduce it, but I could not isolate the root cause yet

**Comment by cateiru** [comment]
This seems to be a problem that occurs when the version of Node.js is different between build and runtime.

Alpine Linux is built with Node 14, so the error occurs with Node 16.
https://github.com/ranisalt/node-argon2/blob/master/.github/workflows/release.yml#L71

The solution is to run the build in source with the `npm_config_build_from_source` flag set to true.

```dockerfile
ARG NODE_VERSION=16.2.0

###
# 1. Dependencies
###

# Build with alpine linux
FROM node:${NODE_VERSION}-alpine as dependencies

WORKDIR /home/node/

ENV NODE_ENV development

# Add build from source flag
ENV npm_config_build_from_source true

# Install the tools needed for the build
RUN apk add make g++ python3 git
RUN npm i -g node-pre-gyp

COPY tsconfig.json package.json *package-lock.json ./
RUN npm ci

COPY ts ./ts
# "prod-build" on production
RUN npm run setup && \
    npm prune --production

###
# 2. Application
###

FROM node:${NODE_VERSION}-alpine
WORKDIR /home/node/

COPY --from=dependencies /home/node/node_modules node_modules
COPY --from=dependencies /home/node/built built

COPY package.json ./

ENV PATH="$PATH:/home/node/node_modules/.bin"

RUN chown -R node:node /home/node
USER node

ENV NODE_ENV production

# "start" on production
CMD ["npm", "run", "start"]
```

**Comment by ranisalt** [comment]
> This seems to be a problem that occurs when the version of Node.js is different between build and runtime.

Interestingly, this seems to be only happening with Alpine. I can understand why it happens, but I was expecting `node-addon-api`  to get around those differences in versions. In this case, it may be related to musl in a corner case that NAA didn't expect.

**Comment by testtestingtester** [comment]
Getting same error...tried everything I could think of...alpine image fails...node image fails...version 0.27.2 fails...anyone knows why it fails?

```
Error: /home/node/api/node_modules/argon2/lib/binding/napi-v3/argon2.node: invalid ELF header
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1239:18)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
    at Module.require (node:internal/modules/cjs/loader:1057:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/home/node/api/node_modules/argon2/argon2.js:6:25)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
    at Module.require (node:internal/modules/cjs/loader:1057:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/home/node/api/src/app.module.ts:8:1)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
```

```
ARG NODE_VERSION=16

###########
# INSTALL #
###########

FROM node:${NODE_VERSION} As install

# 👉 Security: do not use the `root` user.
ENV USER=node

# You can not use `${USER}` here, but reference `/home/node`.
ENV PATH="/home/node/.npm-global/bin:${PATH}"
# 👉 The `--global` install dir
ENV NPM_CONFIG_PREFIX="/home/node/.npm-global"

# All subsequent commands are run as the `node` user.
USER "${USER}"

# Pre-create the target dir for global install.
RUN mkdir -p "${NPM_CONFIG_PREFIX}/lib"

WORKDIR /home/node/api

COPY ./tsconfig*.json ./package*.json ./

# RUN chown -R node:node /home/node

# Install python/pip
# ENV PYTHONUNBUFFERED=1
# RUN apk add --update --no-cache python3 && ln -sf python3 /usr/bin/python
# RUN python3 -m ensurepip
# RUN pip3 install --no-cache --upgrade pip setuptools

# 👉 Configure NPM, so pkg get installed with correct credentials.
# Avoids `chmod u+x $DIR` and other workarounds.
RUN npm --global --quiet --no-progress install \
    && npm cache clean --force

#########
# BUILD #
#########

FROM node:${NODE_VERSION} As build

WORKDIR /home/node/api

COPY ./tsconfig*.json ./package*.json ./

COPY --from=install /home/node/api/node_modules ./node_modules

COPY . .

ENV NODE_ENV=production

RUN npm ci --only=production && npm cache clean --force

RUN npm run setup && npm prune --production

RUN npm run build

##############
# PRODUCTION #
##############

FROM node:${NODE_VERSION} As production

WORKDIR /home/node

COPY --from=build /home/node/api/node_modules ./node_modules
COPY --from=build /home/node/api/dist ./dist

ENV PATH="$PATH:/home/node/api/node_modules/.bin"

RUN chown -R node:node /home/node/api
USER node

ENV NODE_ENV production

CMD [ "node", "dist/src/main.js" ]
```

```
version: '3.8'

services:
  db:
    # image: mongo # container image to be used
    # restart: always 
    # ports: # expose ports in “host:container” format
    #   - 27017:27017
    # environment: #env variables to pass into the container
    #    MONGODB_DATABASE: zombies
    image:  postgres
    restart: always 
    ports:
      - "${DATABASE_PORT}:5432"
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  dev:
    container_name: zombies_dev
    image: zombies-dev:1.0.0
    build:
      context: .
      target: install
      dockerfile: ./Dockerfile
    working_dir: /home/node/api
    command: npm run start:dev #:debug
    ports:
      - 3000:3000
      # - 9229:9229
    networks:
      - zombies-network
    volumes:
      - .:/home/node/api
      # - /home/node/api/node_modules
    restart: unless-stopped
  prod:
    container_name: zombies_prod
    image: zombies-prod:1.0.0
    build:
      context: .
      target: production
      dockerfile: ./Dockerfile
    working_dir: /home/node/api
    command: npm run start:prod
    ports:
      - 3000:3000
      - 9229:9229
    networks:
      - zombies-network
    volumes:
      - .:/home/node
      - /home/node/api/node_modules
    restart: unless-stopped

networks:
  zombies-network:
```

project url https://github.com/testtestingtester/zombies-angular-nestjs
