### ISSUE TITLE
argon2.node: Exec format error on docker container

### ISSUE THREAD

**Issue by TusharRoy23** [ranisalt/node-argon2#367]
### Expected behaviour
Should run the application properly

### Actual behaviour
`Error: Error loading shared library /app/node_modules/argon2/lib/binding/napi-v3/argon2.node: Exec format error`

### Environment
**Docker:** 20.10.17

**Node version:** node:16.18.1-alpine
**argon2:** ^0.30.3

Is anyone having the same issue?

**Comment by ranisalt** [comment]
You are probably building the application in an architecture and running in another. Are you running `yarn install` locally and then mounting `node_modules` into the Alpine container?

**Comment by TusharRoy23** [comment]
> You are probably building the application in an architecture and running in another. Are you running `yarn install` locally and then mounting `node_modules` into the Alpine container?

`fooddev` is the service. Can you tell me what's wrong here?
sorry, pasted the whole file.

```
version: '3.1'
services:
  db:
    container_name: mongodb
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGODB_DATABASE}
    ports:
      - ${MONGODB_PORT}:${MONGODB_PORT}
    volumes:
      - ./mongodb:/data/db
      - ./init-dev-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    restart: unless-stopped
    networks:
      - food_dev_api
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: unless-stopped
    ports:
      - ${MONGO_EXPRESS_PORT}:8081
    environment:
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
      - ME_CONFIG_MONGODB_AUTH_DATABASE=${MONGODB_DATABASE}
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGO_EXPRESS_USERNAME}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_EXPRESS_PASSWORD}
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGODB_ROOT_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGODB_ROOT_PASSWORD}
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - db
    networks:
      - food_dev_api
  fooddev:
    container_name: food-dev
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile-dev
    image: food-api
    env_file:
      - ./env/.dev.env
    volumes:
      - .:/app # create volumn in current directory of container
      - /app/node_modules # anonymus/unnamed volumn in container
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - food_dev_api
networks:
  food_dev_api:
    driver: bridge

volumes:
  mongodb:
```
